### ISSUE TITLE
Adding Dynamic Fields

### ISSUE THREAD

**Issue by DanielMaestro** [NonFactors/MVC6.Grid#100]
<h3>Description</h3>
I have been looking for adding dynamic fields having the following structure:

````C#
public abstract class DynamicFieldBase
{
     public string FieldValue { get; set; }
     public virtual string FieldName { get; set; }
     public virtual int FieldDisplayOrder { get; set; }
     public virtual System.TypeCode FieldType { get; set; }
}
public class ProductDynamicField : DynamicFieldBase
{
    /*Some Properties*/
}
public class Product
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public List<ProductDynamicField> ProductDynamicFields { get; set; }
}
````
Giving the following data:
````C#
var model = new List<Product>()
{
    new Product()
    {
        ProductId = 1,
        ProductName = "Galaxy S7 Edge",
        ProductDynamicFields = new List<ProductDynamicField>()
        {
            new ProductDynamicField()
            {
                FieldName = "Brand",
                FieldType = TypeCode.String,
                FieldDisplayOrder = 1,
                FieldValue = "Samsung"
            },
            new ProductDynamicField()
            {
                FieldName = "Color",
                FieldType = TypeCode.String,
                FieldDisplayOrder = 1,
                FieldValue = "Silver"
            }
        }
    },
    new Product()
    {
        ProductId = 2,
        ProductName = "P10 Lite",
        ProductDynamicFields = new List<ProductDynamicField>()
        {
            new ProductDynamicField()
            {
                FieldName = "Brand",
                FieldType = TypeCode.String,
                FieldDisplayOrder = 1,
                FieldValue = "Huawei"
            },
            new ProductDynamicField()
            {
                FieldName = "Color",
                FieldType = TypeCode.String,
                FieldDisplayOrder = 1,
                FieldValue = "Black"
            }
        }
    }
};
````
It have to show the following table:

Product Id|Product Name|Brand|Color
----------|------------|-----|-----
1|Galaxy S7 Edge|Samsung|Silver
2|P10 Lite|Huawei|Black

I did it work, adding some functionality in the code, however I found some troubles when filtering and ordering. I would like to add this feature in the code and help this project to grow.

**Comment by Muchiachio** [comment]
If you managed to add it through the existing api, filtering and sorting should work already.
How would you handle exceptions in properties? And why do we need `DynamicFieldBase` class?
Because it duplicates existing functionality in grid column classes. Also it seems like a lot of work would be needed to actually prepare the column data in advance for it to work. I was expecting it to be more like `columns.AddPropertiesAsColumnsFrom<TModel>()` and that's it for the default case.

**Comment by DanielMaestro** [comment]
Actually I wrote a new Method in the `GridColumnsClass<T>` and ` IGridColumnsOf<T>` :

````C#
public virtual void AddDynamicFields<TValue>(Expression<Func<T, IEnumerable<TValue>>> expression)
	where TValue : DynamicFieldBase
{
	var entity = Grid.Source?.FirstOrDefault();
	if (entity != null)
	{
		var fields = expression.Compile()(entity).Cast<DynamicFieldBase>().OrderBy(e => e.FieldDisplayOrder).ToArray();
		if (fields != null)
		{
			for (var index = 0; index < fields.Length; index++)
			{
				this.AddDynamicColumns(expression, fields[index].FieldType, index).Titled(fields[index].FieldName);
			}
		}
	}
}
````
And this method is called in the partial view as follows:
````
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.ProductId);
        columns.Add(model => model.ProductName);

        columns.AddDynamicFields(model => model.ProductDynamicFields);
    })
    .Pageable(pager =>
    {
        pager.PagesToDisplay = 10;
        pager.RowsPerPage = 10;
    })
    .Filterable()
    .Sortable()
)
````
The method `AddDynamicColumns` is a extension for `GridColumnsClass<T>` and contains something like this:
````C#
internal static IGridColumn<EType> AddDynamicColumn<EType, DCType>(this GridColumns<EType> list, Expression<Func<EType, IEnumerable<DCType>>> expression, TypeCode typeCode, int index)
    where EType : class
    where DCType : DynamicFieldBase
{
    IGridColumn<EType> result;

    switch (typeCode)
    {
        /* Cases for each TypeCode */
        default:
        case TypeCode.String:
            result = list.Add(GetExpression<EType, string>(expression.Body, expression.Parameters[0], index));
            break;
    }
    return result;
}

internal static Expression<Func<EType, RType>> GetExpression<EType, RType>(Expression body, ParameterExpression parameter, int index)
    where EType : class
{
    var left = Expression.Property(body, "Item", Expression.Constant(index));
    var memberExpression = Expression.Property(left, "FieldValue");
    var result = Expression.Lambda<Func<EType, RType>>(memberExpression, parameter);
    return result;
}
````
I think it can and should be improved, but this is the preliminary code that works. I thought about the method you mentioned before `AddPropertiesAsColumnsFrom<TModel>()` but I couldn't figure how to show the porperty names and select the types.

Please, if you think about a better way to solve this or if you think this sucks, feel free to tell me and we can find a better solution.

**Comment by Muchiachio** [comment]
Property names are taken from `DisplayAttribute` or set by `.Titled` method, so dynamic add could take  `DisplayAttribute` as a default, because setting them by hand isn't that "dynamic" anymore.

> handle the value type

What do you mean by that?

As for your suggested solution, I still don't like the `DynamicFieldBase`, because if user would need to build that kind of arrays, we would be better off with allowing direct grid column adds in a form of

```C#
// building columns, almost the same way as dynamic ones
// with order being the same as insert order into columns
// and type based on property type with a specified name
myDynamicColumns.Add(new GridColumn { Title = "Silver", Name = "Color" });

// and in the grid code
columns.AddRange(myDynamicColumns);
// or
columns.AddRange(model => model.MyDynamicColumns);
// or just allowing dynamic add, which would allow setting dynamic title too
columns.Add("Color").Titled(GetTitleForProperty("Color"));
```

Of course making a `columns.AddAll<TModel>()` is still an options, but that would definitely require grid column attribute which doesn't feel "dynamic" either.

**Comment by Muchiachio** [comment]
Hi, we tried prototyping this and talking with existing grid users who already make dynamic columns and we got to the conclusion that the grid already has all the necessary API to makes this work without the need for creating another layer on top of that. Because it would only add restrictions, like additional attribute on domain model, or no easy way to reorder them dynamically or change expressions as opposed to creating them by hand.

**Comment by Sumon00364** [comment]
How can i call ajax request or call api for .net core razor pages mvc6 grid without create any partial page......?

**Comment by Muchiachio** [comment]
It works by loading a new grid html, if you can somehow create that without partial view it should work.
But if you need that kind of a grid, I would recommend using a full javascript one.
