### ISSUE TITLE
Per-row HTML attributes

### ISSUE THREAD

**Issue by skinkade** [NonFactors/MVC6.Grid#101]
A `RowAttributed` to correspond with `Attributed`, like `RowCss` and `Css`, would be extremely useful.

For a use case, being able to set an HTML attribute for the model's primary key would make it quite easy to e.g. make AJAX requests pertaining to a specific row.

**Comment by Muchiachio** [comment]
Why is `.RowCss` not enough?

**Comment by Muchiachio** [comment]
Yes, was looking at this while I was adding `.Attributed`, and it's harder to add on a row, because of a needed row model. And the other thing which made me not do it and that time was that `_Grid.cshtml` partial is getting more and more complex to the point where `write your own grid partial feature` is becoming too hard to do. So I'm not sure if I should go for it or not at this time.
