### ISSUE TITLE
how to post data from datagrid to server

### ISSUE THREAD

**Issue by ProfMaxSilva** [NonFactors/MVC6.Grid#123]
Hello Muchiachio, first of all, I would like to thank you for the excellent work. Congratulations!
I'm from Brazil, I've been following and using some of his works.
Well, I would like to know how I do to post the network data, use Asp Net Core because when I send to the client or even it is not for server.
Example
1- Sending data to the client
![image](https://user-images.githubusercontent.com/26154929/37658822-2ff9def0-2c2d-11e8-9026-99aba6c5a574.png)
2 - Result
![image](https://user-images.githubusercontent.com/26154929/37658881-4fa9c076-2c2d-11e8-9c32-3102eb2a9111.png)
3 - Sending data to the server
![image](https://user-images.githubusercontent.com/26154929/37658931-6c86cd56-2c2d-11e8-86f7-19adfa4d8e38.png)
**Grid data is lost on back to the server**

Sorry for the bad English (Google translator).
Thank you

**Comment by Muchiachio** [comment]
Grid data is lost because simple `<td>` tag's are not posted back from inside the form.
You would have to render raw html inputs and disabled encoding with `.Encoded(false)` for them to be posted back to the server. You can find html cell content examples [here](http://mvc6-grid.azurewebsites.net/Column/Encoding).

**Comment by ProfMaxSilva** [comment]
thank you. I will try this.
