### ISSUE TITLE
_Grid.cshtml Analyzer/Compiler warning

### ISSUE THREAD

**Issue by fdbva** [NonFactors/MVC6.Grid#165]
Hello.

It's nothing major, maybe the most useless issue ever, but I get some warnings in the file `_Grid.cshtml`

In these lines 
`@Html.Partial(Model.FooterPartialViewName, Model)`
`@Html.Partial(Model.Pager.PartialViewName, Model.Pager)`

I get the message: `Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync`

I fix it changing `Html.Partial` to `await Html.PartialAsync`.

I also get `</!table>` `End tag is missing start tag`. The starting tag is there, but concatenated with `@(Model.Attributes)`.

And the last one `tfoot`, `thead` and `tbody` `cannot be nested inside element 'div'`.

The only one I change when I upgrade is the `PartialAsync` though.

**Comment by Muchiachio** [comment]
Yes there was an issue with partial implementation when model was passed as an async result.
It's not applicable here, but I can move to async method to get that sweet -1 warning :sparkles:

As for other warnings, I'm not sure. Rendering `<table >` instead of `<table>` just makes me sad :smiley:
But it could be fixed with grid tag helpers later on.
