### ISSUE TITLE
Character encoding when exporting

### ISSUE THREAD

**Issue by fdbva** [NonFactors/MVC6.Grid#174]
Hi.

It's a very similar problem to this, I think: [Encoding issue when exporting #161](https://github.com/NonFactors/MVC6.Grid/issues/161)

I wasn't sure if I should have opened a new issue or posted there.

As I understand, the solution used for that case was using `columns.Add(model => model.YourProperty).Encoded(false);`.

Explaining my issue from the start:
I want to write several latin characters. In my debug example I'm focusing in the `Ê` character.
The original file I read is `ANSI 1252`, but it reads correctly and when I debug and `mouseover` it appears correctly.

In debug mode, inside the `foreachloop` and the `StreamWriter`, I can see the `Model` in the `gridRow` correctly have the `field` with the `Ê` character.
After I do the `column.ValueFor(gridRow).ToString()` it changes to `&#xCA;`

I have over 20 different `Models` with over 20 `fields` on most of them, with several `fields` from each needing the `Encoded(false)`, but not all of them.

Do I understand the problem and solution correctly? Is there a better option for this case?

Thanks a lot!

**Comment by Muchiachio** [comment]
There are multiple ways to do it, so what fits you best.

If you are exporting based on the example I provided, you can iterate over all the columns and set the encoding to false (only when exporting) or disable encoding temporary while you are getting the values.
I don't think that avoiding encoding for all colums while exporting will do something bad to the excel.
```
foreach (IGridColumn column in grid.Columns)
{
    column.IsEncoded = false;
    sheet.Cells[row, col++].Value = column.ValueFor(gridRow);
    column.IsEncoded = restoredValue;
}
```

Other option would be to use `IHtmlContent.WriteTo(TextWriter, HtmlEncoder)` function with no encoding instead of just `ToString`, but it requires a temporary stream to write to.

**Comment by fdbva** [comment]
`null` gives an `exception` when I run. I'll try to find the `HtmlEncoder` that does nothing.

**Comment by Muchiachio** [comment]
If you won't find it you can implement your own, but of course that's just additional overhead.

**Comment by fdbva** [comment]
Tried `value.WriteTo(streamWriter, NullHtmlEncoder.Default);`, it seems to be what you mentioned, but it's still writing it wrong when I comment out the `column.IsEncoded = false;`

**Comment by fdbva** [comment]
As I might be doing something else wrong, this is the whole code:
```csharp
var memoryStream = new MemoryStream();
var streamWriter = new StreamWriter(memoryStream, Encoding.UTF8);
foreach (var column in grid.Columns)
{
    streamWriter.Write(column.Title);
    streamWriter.Write(CsvSeparator);
}

streamWriter.WriteLine();

foreach (var gridRow in grid.Rows)
{
    foreach (var column in grid.Columns)
    {
        //var originalEncoding = column.IsEncoded;
        //column.IsEncoded = false;

        var value = column.ValueFor(gridRow);

        value.WriteTo(streamWriter, NullHtmlEncoder.Default);

        //streamWriter.Write(value);
        streamWriter.Write(CsvSeparator);

        //column.IsEncoded = originalEncoding;
    }

    streamWriter.WriteLine();
}

streamWriter.Flush();
memoryStream.Seek(0, SeekOrigin.Begin);

return new FileStreamResult(memoryStream, "text/csv")
{
    FileDownloadName = $"xpto.csv"
};
```

**Comment by Muchiachio** [comment]
Sorry I completely forgot that I'm encoding by hand [here](https://github.com/NonFactors/MVC6.Grid/blob/v4.0.1/src/Mvc.Grid.Core/Columns/GridColumn.cs#L64-L67), so removing encoding is the only sane way now.
I will see if I can move to raw values in the future , because it will require breaking changes anyway.

**Comment by fdbva** [comment]
Should I close the issue? I consider it resolved, but I'm not sure how to proceed.

**Comment by Muchiachio** [comment]
Disabling column encoding when exporting is the way to go for now.
