### ISSUE TITLE
Non Dropdown Option as 2nd Option in Multifilter

### ISSUE THREAD

**Issue by nickwade-phl** [NonFactors/MVC6.Grid#189]
Is it currently possible, or would it be possible to add in the ability to designate the secord query box in a MultiFilterable column to be an input box, while the first is a lookup?

For example

![image](https://user-images.githubusercontent.com/46602385/53572753-fcaece80-3b39-11e9-80ce-a9c28c0aded2.png)

(excuse my quick mockup)

**Comment by Muchiachio** [comment]
It's possible only if you register your own string filter which has `renderFilter(name)` overridden. Name parameter for second filter is `"second"` and `this.column.filter.hasOptions` has the information about option use, you can see default implementation [here](https://github.com/NonFactors/MVC6.Grid/blob/v4.0.3/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L742).

I don't think I will be implementing this, because it looks like an edgy case.

**Comment by nickwade-phl** [comment]
No problem, thanks for the insight.
