### ISSUE TITLE
MVC Grid TagHelper

### ISSUE THREAD

**Issue by neman** [NonFactors/MVC6.Grid#199]
Do you plan to refactor the grid to be used as TagHelper? Do you have some plans for it? Any contribution help needed?

**Comment by Muchiachio** [comment]
The last time I tried it didn't support nesting with a shared state, does it do now?

**Comment by neman** [comment]
Do you have some prototype to elaborate on?
Have you considered tag helper API, how should it be used, no matter the current implementation details?

**Comment by NemanjaTod** [comment]
If grid could be refactored as TagHelper that would be great. If we can help somehow just tell us :)

**Comment by Muchiachio** [comment]
Well the issue I run into instantly is that grid doesn't know about it's columns and column helpers can't use `asp-for` or similar to declare it's properties on the `IEnumerable<T>` for example
```HTML
<div class="mvc-grid" model="Model">
    <table>
        <thead>
            <th column-for="Name"></th>
        </thead>
    </table>
    <tbody>
    </tbody>
</div>
```
`th` tag helper can't use `ModelExpression` because the model is enumerable and not the `<T>` itself. Also `tbody` tag helper would need to know the source and all the column declarations to render the rows. I saw some discussion on making these types of tag helper available years ago, but didn't hear any knew about it.

**Comment by Muchiachio** [comment]
So is this doable? Or it didn't change?
