### ISSUE TITLE
Suggestion: Simple Filter Mode

### ISSUE THREAD

**Issue by M-A-R-K-13** [NonFactors/MVC6.Grid#207]
Here is a suggestion: How about a filter mode without buttons and pop-ups? Only input fields underneath row headers, defaulted to “contains”, refreshing table as you type.

**Comment by Muchiachio** [comment]
Ahem http://mvc6-grid.azurewebsites.net/Grid/FilterModes

**Comment by M-A-R-K-13** [comment]
Thanks for your reply, interesting. I implemented a global search following the instructions on your website. It filters all columns as you type. I am quite happy with the performance. I would have assumed that filtering a single column would be even faster. No?

Also, I thought it would be nice to have a filter option without pop-ups offering advanced options. Some users don’t need them and feel confused.

**Comment by Muchiachio** [comment]
On small tables it's ok, but if you have a site with more users and a bit bigger data set it you start feeling it in cpu usage and average rps. It would also not work on inline column filters, because the grid is repainted on every request so user is not able to keep input focus while typing.

As for no filters, I would just hide them through css, because filters can work without them (using enter key).

**Comment by M-A-R-K-13** [comment]
Many thanks, I appreciate the time you take to explain what’s going on behind the scenes. Hiding the buttons via CSS sounds like a nice solution. Otherwise, I could also upgrade my external search controls to allow for simple filtering.
