### ISSUE TITLE
Can I use .Net core Tag helpers for links

### ISSUE THREAD

**Issue by saurabhnachankar** [NonFactors/MVC6.Grid#213]
Can I use .Net core Tag helpers in Non Factor core mvc grid 6
 such as example : 

**<a asp-for="details"> Details </a>**

I wanted to integrate into my entire project index pages but tag helpers are not currently supported.

Please let me is there any way to use tag helpers in Grid.

```

@model IEnumerable<ErpOneCore.Dapper.division>
@{
    ViewBag.Title = "Division Master";
}

<form class="form-horizontal form-core">
    <div class="col-md-12 grid-form-wall table-condensed  table-striped table-dark">
        @(Html
            .Grid(Model)
            .Build(columns =>
            {
                columns.Add(model => model.divncode).Titled("Division Code");
                columns.Add(model => model.divname).Titled("Division Name");
                columns.Add(model => Html.ActionLink("Details", "Details", new { id = model.id }));
                columns.Add(model => "<a asp-action='details' asp-route-id='model.id'>Details</a>").Encoded(false);
            })
            .Empty("No data found")
            .Filterable()
            .Sortable()
            .Pageable()
            .Css("css-classes") 
            .AppendCss("table-hover")                        
        ) 
        </div>   
</form>
```

**Comment by Muchiachio** [comment]
Tag helpers can't be used as a value like html helpers are, so it's not possible to use it in a grid.

**Comment by saurabhnachankar** [comment]
what is the difference between NonFactors.Grid.Core.Mvc6 and NonFactors.Grid.Mvc6 ?

I though this NonFactors.Grid.Core.Mvc6 package will support tag-helpers.

**Comment by Muchiachio** [comment]
As per nuget description
> Mvc.Grid core dll without content files.

This package provides only dlls needed for grid to run, so you don't have to install content files for say extension projects or projects without UI, also don't look at the grid as it's some kind of magic :)

It would be the same if you would tried to use your static function or any html helper function with a string parameter, tag helpers are rendered directly into response stream and not as a string, thus this doesn't work either
```C#
MyStaticFunction.PrintToFile("<a asp-action='details' asp-route-id='model.id'>Details</a>")
```
or
```C#
Html.Raw("<a asp-action='details' asp-route-id='model.id'>Details</a>")
```
File contents would be the same thing you passed as a parameter, because it's a plain string and tag helpers only converts tags from direct razor html
```
<a asp-action='details' asp-route-id='model.id'>Details</a>
```
