### ISSUE TITLE
Pagination from server side?

### ISSUE THREAD

**Issue by asafgo** [NonFactors/MVC6.Grid#30]
Hello,
I have 1000 rows and I would like to show only 10 in a time.

As I don’t want to bring all the 1000 rows from the database I have "LIMIT 10 OFFSET n" where I am passing a value to n parameter in order to bring the next page.

How can I set Grid pager to the amount of pages that is Count() of the query let's say 1000 rows divided by 10 (100 pages) and displaying the amount of total rows in the Grid.

Also, how can I catch the number pressed on the pager and transfer the number by calling a controller so I will able to know which page to bring to the view?

Thanks in advanced,
AG

**Comment by Muchiachio** [comment]
Grid already does paging in a fast way, its runs two queries.
One loads 20 records from the database and other one counts all the records.

Just make sure you pass `IQueryable` representation of your data, instead of `ToList`'ing it.
For example `return View(context.Set<Account>().OrderBy(account => account.Id))`.

**Comment by asafgo** [comment]
Hi,
I am not using Entity Framework. 
I am using POCO to generate my own CRUD in front of my DB.
thanks,
AG

**Comment by Muchiachio** [comment]
You don't need to use EF, you just need to pass the `IQueryable<TModel>` query object to the view, or you can't make that either in your scenario?

**Comment by asafgo** [comment]
Hi,
No sorry I can only pass a List<T>
I there a way to use it with List instead of IQueryable please?

Thanks,
AG

**Comment by Muchiachio** [comment]
You would need to set [grid pager's](https://github.com/NonFactors/MVC6.Grid/blob/da23f776dce699600724f4cb327d24f558fef749/src/Mvc.Grid.Core/Grids/IGrid.cs#L22) [total rows](https://github.com/NonFactors/MVC6.Grid/blob/da23f776dce699600724f4cb327d24f558fef749/src/Mvc.Grid.Core/Paging/GridPager.cs#L10), with your calculated value.
Grid paging information can be accessed from controller's request query property.

However, if you need to page and query your data by hand. I would recommend not using this grid at all, because you are automatically losing most of it's functionality. Grid features like sorting and filtering can not be automatically applied on already paged result set. It will be easier for you to just `foreach` your table by hand.

**Comment by jjkcharles** [comment]
@asafgo instead of returning the List, you can simply return **listObject.AsQueryable()**, which will take care of your issue without requiring any further changes

**Comment by Muchiachio** [comment]
@jjkcharles it would still require changes, because `listObject.AsQueryable()` is still an in memory collection which would only get wrapped in `IQueryable<T>` object.

**Comment by jjkcharles** [comment]
@Muchiachio missed the part where he mentioned, he didn't want to bring entire dataset to memory!

**Comment by Muchiachio** [comment]
@asafgo did it help?

**Comment by asafgo** [comment]
Yes, thanks you very much for your Grid and your help!

**Comment by abeardsley-vertex** [comment]
For anyone who got here form Google like I did and almost have up, do not!  If you look at the Ajax example at https://mvc6-grid.azurewebsites.net/Grid/Ajax you'll see that IQueryable is returned.  This lets the grid do all the database work server-side in EF/SQL (if that's what you're using like I am).

If the code owner is reading this you might want to update the documentation to really highlight that fact, because it was 100% a requirement for my project.

**Comment by firstdivision** [comment]
For anyone who got here from Google like I did and almost have up, do not! If you look at the Ajax example at https://mvc6-grid.azurewebsites.net/Grid/Ajax you'll see that IQueryable is returned. This lets the grid do all the database work server-side in EF/SQL (if that's what you're using like I am).

If the code owner is reading this you might want to update the documentation to really highlight that fact, because it was 100% a requirement for my project.

**Comment by Muchiachio** [comment]
Will replace `IEnumerables` with `IQueryables` where possible and mention that on the page.
Thought that people know that you do paging like this
```C#
models.Take(20).ToArray(); // in db
```
and not like this
```C#
models.ToArray().Take(20); // in memory
```

**Comment by firstdivision** [comment]
For me it was even more ground-breaking.  I thought I was going to have to read the url parameters on the way in and do all the paging/sorting/filtering myself.  I did not realize that there was code built in on the C# side to handle all that for me, as long as I was returning `IQueryable` and not trying to materialize the query.

I assume I interpreted what was happening correctly.  My OnGet literally just creates a new IQueryable of my ViewModel by selecting from the EF context like `efContext.Things.Select(t => new MyViewModel{...});` and then set my PageModel property with that.  SQL Profiler looked to me like every operation from the grid was being sent down into SQL for me.
