### ISSUE TITLE
I would like to see more examples and have better documentation

### ISSUE THREAD

**Issue by vzdesic** [NonFactors/MVC6.Grid#41]
Dear Muchiachio,

I am sure you are too busy for writing more examples or documentation, but my problem is that I really would like to use this grid in one new and relatively big project written in a ASP.NET Core. I have to be fast now to find out all necessary informations and to decide.

What would you recommend? Surely, I don't expect that you are available to answer to all possible questions here, but what do you suggest? How to exchange informations fast?

Would you recommend me to use grid now, on this stage, in a relatively large application?

Now, I am spending days to find out few things, but without success:
- Filters doesn't work. I just don't know why. This should be simple, but ...
- There is no API specification, so that I know what is possible to catch, which functions are available (like rowClicked, reloadStarted, ...). How can I investigate code to find out available APIs?
- When row is clicked, how can I change row appearance? I wan't to change it to be editable, with all input elements.
- How to block rowClicked event to fire when some CheckBox is clicked inside current row, because in this case user's intention is just element selection?
- If I want to enable adding new item with 'Add row' button located somewhere in the grid. Click on that button should add new empty row (with input elements inside cells), how to do it?
- In general, I don't know how to change row only on a client side?
- If I want to show pop-up, actually, form with data of current row on rowClicked, should I use jquery for that purpose?
- and so on ...

Sorry for this long message.

I am looking forward to hear something from you.

Thanks,
Vedran

**Comment by Muchiachio** [comment]
If you know other good documentation and example pages, share with me so I can accordingly improve mine. Also you should ask questions in [documentation repo](https://github.com/NonFactors/MVC6.Grid.Web), so I can improve on pages, based on your feedback.

As for your questions, if you know other grids with better documentation and examples use them. I can't really recommend or not without your system context :) I do already use it in large applications and don't have much problems. 

> Filters doesn't work. I just don't know why

Filters may not work if they are not enabled or they can't be filtered, because of their type or complex expression. However everything can be forced with `.Filterable(true).FilteredAs("Text")` for example. It most likely won't work, but it can be forced to filter, unless there are bigger configuration and such.

> There is no API specification, so that I know what is possible to catch, which functions are available (like rowClicked, reloadStarted, ...). How can I investigate code to find out available APIs?

All api is exposed by [examples page](http://mvc6-grid.azurewebsites.net/), if you search for `row click` or `reload events` you should find example usages on these or other javascript methods. If they are not there, they are undocumented and should not be used.

> When row is clicked, how can I change row appearance. I wan't to change it to be editable, with all input elements?

What's all javascript, you can either use grid's `rowClicked` event or bind your own through javascript.

> How to block rowClicked event to fire when some CheckBox is clicked inside current row, because in this case user's intention is just element selection?

`rowClicked` exposes event information through `e` parameter, which can be prevented by either `preventDefault`, `stopPropagation` or other javascript methods. But again you don't have to use `rowClicked` as you can just bind your own.

> If I want to enable adding new item with 'Add row' button located somewhere in the grid. Click on that button should add new empty row, how to do it?

Again all javascript, [here](http://stackoverflow.com/a/6473259/4110026) are some code examples.

> In general, I don't know how to change row only on a client side?

Not sure what you are trying to do here, but I guess javascript?

> If I want to show pop-up, actually form with data of current row on rowClicked, should I use jquery for that purpose?

Yes, I would use jQuery.

> and so on ...

I do wonder if these questions are rising from grid being hard to get, or just people not knowing the web development that well? What do you think? :)

**Comment by vzdesic** [comment]
First of all, thanks a lot for quick reply!

Actually, your Grid is very good, and is easy to use. That is not a problem. I don't know for the others, but I can say what is problem in my case. So, when I am switched between projects and technologies (some of them not web at all), it is very important that I have some available resources (documentation, some real code examples etc.) to be as much productive as I can in this process. For example, I used jQuery and jqGrid a lot. There is plenty of documentation and examples online, and because I know what is possible and what is not, I can find what I need very fast. When I forgot something I remember it just by seeing some example, almost without waste of the additional time.

I am sure that after week or so I will be the same productive with this grid. I will continue to use it. You got me! I just asked my questions to shorten my learning curve for a few days. All my problems are solvable and I will continue with your grid. Also I will try to add some examples to existing web repo, if you will allow that.

Thanks,
Vedran

**Comment by Muchiachio** [comment]
> Also I will try to add some examples to existing web repo, if you will allow that.

Yes, create issues in the web repo, if you would like to see new examples or find existing ones confusing.
As I don't really want add examples showing how to use javascript :)

**Comment by vzdesic** [comment]
Ok, clear!
