### ISSUE TITLE
Use ShortName for Title

### ISSUE THREAD

**Issue by Rfvgyhn** [NonFactors/MVC6.Grid#5]
When the grid figures out the title for a column, it should check for [ShortName](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.displayattribute.shortname%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) via [GetShortName](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.displayattribute.getshortname(v=vs.110).aspx) and fallback to `GetName` if it's not specified.

**Comment by Muchiachio** [comment]
I agree that short name could be used. But shouldn't it be the other way around? Use `GetName` and then fallback to `GetShortName`? I would want to use `GetName` first, because people are more familiar with `GetName` notation from all the examples ASP.NET is providing. Unless there is deeper meaning to that attribute?

**Comment by Muchiachio** [comment]
Oh, I think I get it, using short name would be better for the grid column, so that they don't span across half the table on longer names right?

**Comment by Rfvgyhn** [comment]
Yeah. I think `ShortName` is specifically for grid headers wheres `Name` is for everything else.

> The short name is used as the grid column label for a UI element that is bound to the property that is annotated with this attribute.
